### ISSUE TITLE
Markers jump around

### ISSUE THREAD

**Issue by fredriknilbrink** [Vejron/CpSessionServer#3]
Strange marker behaviour. Marker moves even though image recognition is super steady. Concerns mostly Eindhoven markers. Didnt check for lightning conditions etc.

**Comment by Vejron** [comment]
I did some digging into the issue. Seems like the tableId is set when the PiCpServer spins up an instance of the PiCpTracker via the -t=<tableId> switch. this Id is set in table.config.js witch should reside in something like  ~/share/picpserver/table.config.js. check this for each table

**Comment by fredriknilbrink** [comment]
Even the markers at table 15 (which I'm sure are unique ones) are behaving strangly. 
Conclusion from testing:
* UDP message coming in is steadily and correct (tracking box working fine seems fine)
* Testmarker in database has the correct information (same as UDP message)

PROBLEM!!
* Markers for table 15 are NOT drawn in the correct position. They move and jump around and kind of eventually want to assume the same position !!! There seems to be some logical error in cpSessionServer.

**Comment by Vejron** [comment]
Think I might have found the culprit.. working on a soulotion

**Comment by Vejron** [comment]
I think the testMarker collection was ever only meant to hold markers for one table. on each consecutive write I suspect that I wrote a new array of markers but then also deleted the old one, so that the collection only ever consisted of the "latest" batch of markers from one table. I made a new object now on the server side called MarkerCache that holds all markers from all tables in an array of arrays structure. The markerTest collection now basically contains that. 

There are some changes on the client side that has to be made to make it work tough as its not structured the same way. changes has to be made in threeView.js when I fetch the collection. Thing is
I can't debug as I have no table on my subnet :(. 

Important! Do a meteor reset to clean the db  before testing with the new code.

**Comment by fredriknilbrink** [comment]
OMG. It's working :-)
Had som problems reading from the database, but now I've updated the table update prototype and threeview ... GREAT! Had some followup trail issues, but I guess I need to update the updates for trails and markers also.

![trails](https://cloud.githubusercontent.com/assets/5427399/14705701/1abaa67a-07bb-11e6-90a9-a14a42d6e64e.png)

**Comment by fredriknilbrink** [comment]
Resolved this by removing the feature "T3D.randomPositionAroundTable()" ... and setting [0,0,0]. It actually looks nicer as well... Updated minmovedistance in table_configuration file for tracker to 5cm. Now nothing is moving when it should not. Thanks Björn, case closed.
